name: InstanceEditor
version: '1.0-SNAPSHOT'
main: org.joebobilly.appleattack.InstanceEditor
api-version: '1.21.11'
depend: [Holograms]
commands:
  positionlist:
    description: "Provides you with a position list item used for defining mob spawners"
    usage: "/positionlist"
    aliases: [poslist, plist, pl]
    permission: instanceeditor.positionlist
    permission-message: "You do not have permission to use this command"
  createentityspawner:
    description: "Allows you to create NPC spawners"
    usage: "/createentityspawner npc [npc type id]\n/createentityspawner mob [mob type id] [max spawned]"
    aliases: [ createnpcspawner, createnpc, placenpc, npcadd, createmobspawner, createmob, placemob, mobadd ]
    permission: instanceeditor.createentityspawner
    permission-message: "You do not have permission to use this command"